# This will run on Travis' 'new' container-based infrastructure
sudo: true

# Setup for Ubuntu Bionic (18.04)
dist: bionic

language:
  - python

python:
  - 3.6

git:
  submodules: false

# Environment variables
env:
  global:
    - GH_REPO_URL: github.com/slaclab/kpix
    - PACKAGE_DIR: $HOME/packages
    - MINICONDA_DIR: $PACKAGE_DIR/miniconda
    - DOWNLOAD_DIR: ${HOME}/download
    - DOWNLOAD_URL: ${GH_REPO_URL}/releases/download/${TRAVIS_TAG}/rogue_${TRAVIS_TAG}.zip

# Install dependencies
addons:
  apt:
    packages:
      - python3
      - flake8
      - jq


stages:
    - name: software_check
      if: (type == pull_request) or (tag IS present) or (branch == master)
    - name: deploy_tag
      if: tag IS present


# Generate and deploy documentation
jobs:
  include:
    - &software-check-stage
      stage: software_check
      name: "Check Python for Errors"
      script:
        - cd $TRAVIS_BUILD_DIR
        - python3 -m compileall -f firmware/common/python
        - flake8 --count firmware/common/python


    - &deploy-conda-stage       # Conda for linux
      stage: deploy_tag
      name: "Deploy Conda"
      before_install:
        # Prepare folders
        - mkdir -p $MINICONDA_DIR
        - mkdir -p $DOWNLOAD_DIR

      install:
        # Install Anaconda for the right architecture (linux or osx)
        - pip install -r requirements.txt
        # Download and unzip tag zipfile        
        - cd $DOWNLOAD_DIR
        - python $TRAVIS_BUILD_DIR/releaseDownload.py --repo="slaclab/kpix" --tag="$TRAVIS_TAG"
        - cd $MINICONDA_DIR
        - wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes
        - conda install conda-build anaconda-client conda-verify
        - conda update -q conda conda-build


      script:
        # Build conda package
        - travis_wait 60 conda build --debug conda-recipe --output-folder bld-dir -c tidair-tag -c conda-forge

      after_success:
        # Upload conda package
        - anaconda -t $CONDA_UPLOAD_TOKEN_TAG upload bld-dir/`echo $TRAVIS_OS_NAME`-64/*.tar.bz2
